todo-aspnetmvc-ui/Controllers/RemindersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using todo_aspnetmvc_ui.Models;
using todo_aspnetmvc_ui.Models.Repo;

namespace todo_aspnetmvc_ui.Controllers
{
    public class RemindersController : Controller
    {
        private readonly IReminderRepository _reminderRepo;
        private readonly IItemRepository _itemRepo;

        public RemindersController(IReminderRepository reminderRepo, IItemRepository itemRepo)
        {
            _reminderRepo = reminderRepo;
            _itemRepo = itemRepo;
        }

        [HttpPost]
        [Route("Reminders/Create/{itemId:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int itemId)
        {
            var item = await _itemRepo.GetItemByIdAsync(itemId);
            if (item == null)
            {
                return NotFound();
            }
            var reminder = new Reminder(item.Title, itemId);

            await _reminderRepo.InsertReminderAsync(reminder);
            await _reminderRepo.SaveAsync();

            return RedirectToRoute("default", new { controller = "TodoList", action = "Details", id = item.ListID });
        }

        [HttpPost]
        [Route("Reminders/Delete/{itemId:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int itemId)
        {
            var item = await _itemRepo.GetItemByIdAsync(itemId);
            if (item == null)
            {
                return NotFound();
            }

            await _reminderRepo.RemoveReminderAsync(itemId);
            await _reminderRepo.SaveAsync();

            return RedirectToRoute("default", new { controller = "TodoList", action = "Details", id = item.ListID });
        }

        protected override void Dispose(bool disposing)
        {
            _itemRepo.Dispose();
            _reminderRepo.Dispose();
            base.Dispose(disposing);
        }
    }
}

todo-aspnetmvc-ui/Controllers/TodoItemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using todo_aspnetmvc_ui.Models.Repo;
using todo_aspnetmvc_ui.Models.ViewModels;
using todo_domain_entities;

namespace todo_aspnetmvc_ui.Controllers
{
    public class TodoItemController : Controller
    {
        private readonly IItemRepository _itemRepository;
        private readonly ITodoRepository _todoRepository;

        public TodoItemController(IItemRepository itemRepository, ITodoRepository todoRepository)
        {
            this._itemRepository = itemRepository;
            this._todoRepository = todoRepository;
        }

        [HttpGet]
        [Route("TodoItem/Create/{listId:int}")]
        public async Task<IActionResult> Create(int listId)
        {
            var list = await _todoRepository.GetTodoListByIdAsync(listId);
            if (list == null)
            {
                return NotFound();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("TodoItem/Create/{listId:int}")]
        public async Task<IActionResult> Create(TodoItem item, [FromRoute]int listId)
        {
            var list = await _todoRepository.GetTodoListByIdAsync(listId);

            if (list == null)
            {
                return NotFound();
            }

            try
            {
                item.CreationDate = DateTime.Now;

                if (ModelState.IsValid)
                {
                    await _itemRepository.InsertItemAsync(item);
                    await _itemRepository.SaveAsync();

                    return RedirectToRoute("default", new { controller = "TodoList", action = "Details", id = listId });
                }
            }
            catch (DataException /*dex*/)
            {

                ModelState.AddModelError(string.Empty, "Unable to save changes.Try again, and if the problem persists contact your system administrator.");
            }
            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            TodoItem item = await _itemRepository.GetItemByIdAsync(id);
            List<TodoList> lists = await _todoRepository.GetListsAsync();
            var viewModel = new EditItemViewModel(item, lists);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TodoItem item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _itemRepository.UpdateItem(item);
                    await _itemRepository.SaveAsync();
                    return RedirectToRoute("default", new { controller = "TodoList", action = "Details", id = item.ListID });
                }
            }
            catch (DataException)
            {

                ModelState.AddModelError(string.Empty, "Unable to save changes.Try again, and if the problem persists contact your system administrator.");
            }
            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            TodoItem item = await _itemRepository.GetItemByIdAsync((int)id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            TodoItem item = await _itemRepository.GetItemByIdAsync(id);
            if (item == null)
            {
                RedirectToAction(nameof(Index));
            }

            try
            {
                await _itemRepository.DeleteItemAsync(id);
                await _itemRepository.SaveAsync();
                return RedirectToRoute("default", new { controller = "TodoList", action = "Details", id = item.ListID });
            }
            catch (DataException)
            {
                return RedirectToAction(nameof(Delete), new { id });
            }
        }

        protected override void Dispose(bool disposing)
        {
            _todoRepository.Dispose();
            _itemRepository.Dispose();
            base.Dispose(disposing);
        }
    }
}

todo-aspnetmvc-ui/Controllers/TodoListController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using todo_aspnetmvc_ui.Models;
using todo_aspnetmvc_ui.Models.Repo;
using todo_aspnetmvc_ui.Models.ViewModels;
using todo_domain_entities;

namespace todo_aspnetmvc_ui.Controllers
{
    public class TodoListController : Controller
    {
        private readonly ITodoRepository _todoRepository;
        private readonly IItemRepository _itemRepository;
        private readonly IReminderRepository _reminderRepository;

        public TodoListController(ITodoRepository repository, IItemRepository itemRepository, IReminderRepository reminderRepository)
        {
            this._todoRepository = repository;
            this._itemRepository = itemRepository;
            this._reminderRepository = reminderRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index(ListIndexViewModel model)
        {
            var lists = from l in await _todoRepository.GetListsAsync()
                        select l;

            var reminders = from r in await _reminderRepository.GetRemindersAsync()
                            select r;

            model.Lists = lists;

            if (model.ShowHidedLists != true)
            {
                model.Lists = lists.Where(x => x.IsHided == false);
            }

            model.Reminders = reminders;
            model.CheckboxDescription = "Show hided lists?";

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(TodoListDetailsViewModel model, [FromRoute] int id)
        {
            var list = await _todoRepository.GetTodoListByIdAsync(id);
            var items = list.TodoItems;

            model.List = list;

            if (model.HideCompletedItems == true)
            {
                items = items.Where(x => x.ItemStatus != ItemStatuses.Completed).ToList();
            }

            if (model.ShowWithDueToday == true)
            {
                items = items.Where(x => x.DueDate.Date == DateTime.Today).ToList();
            }

            if (model.HideExpired == true)
            {
                items = items.Where(x => x.DueDate.Date >= DateTime.Today).ToList();
            }

            model.List.TodoItems = items;
            model.HideCompletedDescription = "Hide completed todo items?";
            model.ShowWithDueTodayDescription = "Show todo items with due date today?";
            model.HideExpiredDescription = "Hide expired items?";

            return View(model);
        }


        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        //public ActionResult Create(TodoList list)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            _todoRepository.InsertTodoList(list);
        //            _todoRepository.Save();
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    catch (DataException /*dex*/)
        //    {

        //        ModelState.AddModelError(string.Empty, "Unable to save changes.Try again, and if the problem persists contact your system administrator.");
        //    }
        //    return View(list);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string name)
        {
            ViewData["NameOfListParam"] = String.IsNullOrEmpty(name) ? "" : name;
            try
            {
                TodoList list = new TodoList(name);
                await _todoRepository.InsertTodoListAsync(list);
                await _todoRepository.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            TodoList list = await _todoRepository.GetTodoListByIdAsync(id);
            return View(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TodoList list)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _todoRepository.UpdateTodoList(list);
                    await _todoRepository.SaveAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {

                ModelState.AddModelError(string.Empty, "Unable to save changes.Try again, and if the problem persists contact your system administrator.");
            }
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            TodoList list = await _todoRepository.GetTodoListByIdAsync((int)id);
            if (list == null)
            {
                return NotFound();
            }
            return View(list);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            TodoList list = await _todoRepository.GetTodoListByIdAsync(id);
            if (list == null)
            {
                RedirectToAction(nameof(Index));
            }

            try
            {
                await _todoRepository.DeleteTodoListAsync(id);
                await _todoRepository.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DataException)
            {
                return RedirectToAction(nameof(Delete), new { id });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Hide(int id)
        {
            TodoList list = await _todoRepository.GetTodoListByIdAsync(id);
            list.HideList();
            _todoRepository.UpdateTodoList(list);
            await _todoRepository.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Show(int id)
        {
            TodoList list = await _todoRepository.GetTodoListByIdAsync(id);
            list.ShowList();
            _todoRepository.UpdateTodoList(list);
            await _todoRepository.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Copy(int id)
        {
            var list = await _todoRepository.GetTodoListByIdAsync(id);
            if (list == null)
            {
                return NotFound();
            }

            var copiedList = new TodoList(list.Name, list.IsHided);

            await _todoRepository.InsertTodoListAsync(copiedList);

            await _todoRepository.SaveAsync();

            //var items = list.TodoItems;

            //List<TodoItem> itemsCopied = new List<TodoItem>();

            //list = (await _todoRepository.GetListsAsync()).Last();

            //foreach (var item in items)
            //{
            //    itemsCopied.Add(new TodoItem(item.Title, item.Description, DateTime.Today.AddDays(5), list, item.ItemStatus));
            //}

            //await _itemRepository.InsertItemsRangeAsync(itemsCopied);

            return RedirectToAction(nameof(Index));
        }

        protected override void Dispose(bool disposing)
        {
            _todoRepository.Dispose();
            _itemRepository.Dispose();
            _reminderRepository.Dispose();
            base.Dispose(disposing);
        }
    }
}

todo-aspnetmvc-ui/Views/TodoList/Create.cshtml
@model todo_domain_entities.TodoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TodoList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

todo-aspnetmvc-ui/Views/TodoList/Delete.cshtml
@model todo_domain_entities.TodoList

@{
    ViewData["Title"] = "Delete";
}

<h3 class="text-center">Are you sure you want to delete this?</h3>
<div>
    <h4 class="">TodoList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ListId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

todo-aspnetmvc-ui/Views/TodoList/Details.cshtml
@model todo_aspnetmvc_ui.Models.ViewModels.TodoListDetailsViewModel

@{
    ViewData["Title"] = "Details";
}


<div>
    <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
        <i class="fas fa-check-square me-1"></i>
        <u>@Html.DisplayFor(model => model.List.Name)</u>
    </p>

    <form asp-controller="TodoList" asp-action="Details" asp-route-id="@Model.List.ListId" method="get">

        <div class="form-check mb-3">
            <input class="form-check-input"
                   type="checkbox"
                   asp-for="@Model.HideCompletedItems" />
            <label class="form-check-label" asp-for="@Model.HideCompletedItems">
                @Model.HideCompletedDescription
            </label>
        </div>
        <div class="form-check mb-3">
            <input class="form-check-input"
                   type="checkbox"
                   asp-for="@Model.ShowWithDueToday" />
            <label class="form-check-label" asp-for="@Model.ShowWithDueToday">
                @Model.ShowWithDueTodayDescription
            </label>
        </div>
        <div class="form-check mb-3">
            <input class="form-check-input"
                   type="checkbox"
                   asp-for="@Model.HideExpired" />
            <label class="form-check-label" asp-for="@Model.HideExpired">
                @Model.HideExpiredDescription
            </label>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>

    </form>

    @foreach (var item in Model.List.TodoItems)
    {
        #region Setting color of item status badge
        string color;
        string textColor;
        if (item.ItemStatus == todo_domain_entities.ItemStatuses.Completed)
        {
            color = "success";
            textColor = "light";
        }
        else if (item.ItemStatus == todo_domain_entities.ItemStatuses.NotStarted)
        {
            color = "info";
            textColor = "dark";
        }
        else
        {
            color = "danger";
            textColor = "light";
        }
        #endregion
        <div class="card bg-warning mb-2">
            <div class="card-body text-center d-flex justify-content-between pb-2 pt-2">
                <div>
                    <a class="card-text text-black-50 font-weight-bold stretched-link text-decoration-none"
                       asp-controller="TodoItem"
                       asp-action="Edit"
                       asp-route-id="@item.EntryID">
                        @Html.DisplayFor(modelItem => item.Title)
                    </a>
                    <div class="badge badge-@color text-@textColor ml-2">@item.ItemStatus</div>
                </div>

                <div class="dropright d-inline-block text-black-50" style="position: relative; z-index: 3;">
                    <a data-toggle="dropdown"><i class="fa fa-ellipsis-v fa-2x waves-effect" style="transform: rotate(0);"></i></a>
                    <div class="dropdown-menu" style="z-index: 5000;">
                        <form class="" asp-controller="Reminders" asp-action="Create" asp-route-id="@item.EntryID" method="post">
                            <div class="">
                                <input type="submit" value="Create reminder" class="border-0 btn-transition btn btn-outline-danger dropdown-item" />
                            </div>
                        </form>
                        <form class="" asp-controller="Reminders" asp-action="Delete" asp-route-id="@item.EntryID" method="post">
                            <div class="">
                                <input type="submit" value="Delete reminder" class="border-0 btn-transition btn btn-outline-danger dropdown-item" />
                            </div>
                        </form>
                        <a class="dropdown-item" asp-action="Delete" asp-controller="TodoItem" asp-route-id="@item.EntryID">
                            <i class="fa fa-trash-o fa-lg"></i>Delete
                        </a>
                        <a class="dropdown-item" asp-action="Edit" asp-controller="TodoItem" asp-route-id="@item.EntryID">
                            <i class="fa fa-pencil fa-fw"></i>Edit
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-footer pt-1 pb-1">
                <div class="blockquote mb-1"><i>Created: @item.CreationDate.ToShortDateString()</i></div>
                <div class="blockquote mb-1"><i>Expiration: @item.DueDate.ToShortDateString()</i></div> 
            </div>
        </div>
    }

</div>
<div>
    <a class="btn btn-outline-light btn-dark" asp-action="Edit" asp-route-id="@Model.List.ListId">Edit list</a> |
    <a class="btn btn-outline-light btn-primary" asp-action="Create" asp-controller="TodoItem" asp-route-id="@Model.List.ListId">Create new todo</a> |
    <a class="btn btn-outline-light btn-success" asp-action="Index">Back to List</a>
</div>

<style>
    i:hover {
        color: #4285F4;
    }

    .dropdown-menu {
        position: fixed;
    }

    .dropdown .dropdown-menu .dropdown-item {
        padding: 1rem;
        margin-left: 0;
        display: inline-block;
    }

        .dropdown .dropdown-menu .dropdown-item:hover {
            box-shadow: 0 8px 17px 0 rgba(0, 0, 0, .2), 0 6px 20px 0 rgba(0, 0, 0, .19);
            color: white;
            background: #4285F4;
        }

    .card-text {
        font-size: 18px;
    }

    .blockquote{
        font-size:14px;
    }
</style>

todo-aspnetmvc-ui/Views/TodoList/Edit.cshtml
@model todo_domain_entities.TodoList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TodoList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ListId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-light btn-dark" asp-action="Create" asp-controller="TodoItem" asp-route-id="@Model.ListId">Create new todo</a> |
    <a class="btn btn-outline-light btn-dark" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

todo-aspnetmvc-ui/Views/TodoList/Index.cshtml
@model todo_aspnetmvc_ui.Models.ViewModels.ListIndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Hello.</h1>
<h2 class="text-center">Today you have @Model.Lists.Count() tasks.</h2>

<div>
    <form asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label class="control-label"></label>
            <input type="text" name="name" class="form-control" value="@ViewData["NameOfListParam"]" />
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-warning" />
        </div>
    </form>
</div>
<form asp-controller="TodoList" asp-action="Index" method="get">

    <div class="form-check mb-3">
        <input class="form-check-input"
               type="checkbox"
               asp-for="@Model.ShowHidedLists" />
        <label class="form-check-label" asp-for="@Model.ShowHidedLists">
            @Model.CheckboxDescription
        </label>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

@if (Model.Reminders.Any())
{
    <div id="myModal" class="modal fade">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Reminders for tasks.</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    @foreach (var item in Model.Reminders)
                    {
                        <div>
                            <p>@item.Title</p>
                        </div>
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="card border-0">
    @foreach (var list in Model.Lists)
    {
        <div class="card bg-primary mb-2">
            <div class="card-body text-center d-flex justify-content-between">
                <div>
                    <a class="card-text text-white font-weight-bold stretched-link text-decoration-none" asp-action="Details" asp-route-id="@list.ListId">@Html.DisplayFor(modelItem => list.Name)</a>
                    <p class="blockquote">@list.TodoItems.Count tasks.</p>
                </div>
                <div class="dropright d-inline-block text-white" style="position: relative; z-index: 3;">
                    <a data-toggle="dropdown"><i class="fa fa-ellipsis-v fa-2x waves-effect" style="transform: rotate(0);"></i></a>
                    <div class="dropdown-menu" style="z-index: 5000;">
                        <a class="dropdown-item" asp-action="Edit" asp-route-id="@list.ListId"><i class="fa fa-pencil fa-fw"></i> Edit</a>
                        <a class="dropdown-item" asp-action="Delete" asp-route-id="@list.ListId"><i class="fa fa-trash-o fa-lg"></i> Delete</a>
                        <form asp-action="Copy" asp-route-id="@list.ListId" method="post">
                            <input type="submit" value="Copy" class="dropdown-item" />
                        </form>
                        <form asp-action="Hide" asp-route-id="@list.ListId" method="post">
                            <input type="submit" value="Hide" class="dropdown-item" />
                        </form>
                        <form asp-action="Show" asp-route-id="@list.ListId" method="post">
                            <input type="submit" value="Show" class="dropdown-item" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<script>
    $('a[data-toggle="dropdown"]').click(function () {
        dropDownFixPosition($(this), $('.dropdown-menu'));
    });

    function dropDownFixPosition(a, dropdown) {
        var dropDownTop = a.offset().top + a.outerHeight();
        dropdown.css('top', dropDownTop + "px");
        //Delete - dropdown.width() if you want menu to be bottom right of link
        dropdown.css('left', a.offset().left - dropdown.width() + "px");
    }
</script>

<style>
    i:hover {
        color: #4285F4;
    }

    .dropdown-menu {
        position: fixed;
    }

    .dropdown .dropdown-menu .dropdown-item {
        padding: 1rem;
        margin-left: 0;
        display: inline-block;
    }

        .dropdown .dropdown-menu .dropdown-item:hover {
            box-shadow: 0 8px 17px 0 rgba(0, 0, 0, .2), 0 6px 20px 0 rgba(0, 0, 0, .19);
            color: white;
            background: #4285F4;
        }

    .card-text {
        font-size: 18px;
    }
</style>